# name: deploy

# "on":
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: lewagon/wait-on-check-action@v1.0.0
#         with:
#           ref: ${{ github.ref }}
#           check-name: 'test'
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#       - run: echo "ğŸ‰ This should send a mail for deployemnt."
#       - run: echo "ğŸ This has been deployed to netflify."
